version: 2
updates:
  - package-ecosystem: "cargo"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "cargo"
    # Files stored in repository root
    directory: "/findlib"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
